apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  type: LoadBalancer
  ports:
  - name: "8010"
    port: 8010
    targetPort: 8080
  selector:
    service: reverseproxy
